name: my_pets
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'  # Use a Dart SDK version that supports null safety

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^0.13.3  # Use a version of http that supports null safety
  carousel_slider: ^4.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/cat2.1.png
